CREATE DATABASE IF NOT EXISTS usersdb;
USE usersdb;

CREATE TABLE IF NOT EXISTS Users (
  Id INT AUTO_INCREMENT PRIMARY KEY,
  Email VARCHAR(150) NOT NULL UNIQUE,
  PasswordHash VARCHAR(200) NOT NULL,
  Name VARCHAR(100) NOT NULL DEFAULT '',
  Address VARCHAR(200) NOT NULL DEFAULT '',
  Phone VARCHAR(50) NOT NULL DEFAULT '',
  Country VARCHAR(100) NOT NULL DEFAULT '',
  Language VARCHAR(50) NOT NULL DEFAULT '',
  Role VARCHAR(20) NOT NULL DEFAULT 'Customer'
);